# Server Configuration
server:
  port: 8080

# DataSource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysqldb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&publicKeyRetrieval=false
    username: root
    password: Alumne2023
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update

  # Security Configuration - OAuth2 for Google
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
